const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.EightDir.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{ancho_Inicial: 0},
	{alto_Inicial: 0},
	{"8Direcciones": 0},
	{Tweeninterpolación: 0},
	{Seno: 0},
	{Seno2: 0},
	{Pi_character: 0},
	{ojo: 0},
	{Teclado: 0},
	{Audio: 0},
	{hablando: 0},
	{boca: 0},
	{ceja: 0},
	{nariz: 0},
	{deslizador: 0},
	{fondo: 0},
	{fondo2: 0},
	{fondo3: 0},
	{diapositivas_01: 0},
	{slides_transp: 0},
	{deDóndeSale: 0},
	{ceja2: 0},
	{fondo_mat: 0},
	{"8Direction": 0},
	{explicacion_slides: 0},
	{factor_ampliacion: 0},
	{factor_reduccion: 0},
	{factor_esquina: 0},
	{reflejado: 0},
	{senalando: 0},
	{anguloDesplazamiento: 0},
	{reduccion_inicial: 0},
	{visible_Pi: 0},
	{y_Pi_inferior: 0},
	{factorAumentoSlide: 0},
	{factorDisminuciónSlide: 0},
	{fotograma_explicación: 0}
];

self.InstanceType = {
	Pi_character: class extends self.ISpriteInstance {},
	ojo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	boca: class extends self.ISpriteInstance {},
	ceja: class extends self.ISpriteInstance {},
	nariz: class extends self.ISpriteInstance {},
	deslizador: class extends self.ISpriteInstance {},
	fondo: class extends self.ITiledBackgroundInstance {},
	fondo2: class extends self.ITiledBackgroundInstance {},
	fondo3: class extends self.ITiledBackgroundInstance {},
	diapositivas_01: class extends self.ISpriteInstance {},
	slides_transp: class extends self.ISpriteInstance {},
	deDóndeSale: class extends self.ISpriteInstance {},
	ceja2: class extends self.ISpriteInstance {},
	fondo_mat: class extends self.ISpriteInstance {},
	explicacion_slides: class extends self.ISpriteInstance {}
}